version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.1
    container_name: elasticsearch
    environment:
      - http.cors.enabled=true
      - discovery.type=single-node
    ports:
      - 9200:9200

  graphana:
    image: grafana/grafana
    ports:
      - 3000:3000